#ifndef MY_OPCODE_H
#define MY_OPCODE_h

#define ADD 1			/*ADD,INTEGER,INTEGER,INTEGER*/
#define SUB 2			/*SUB,INTEGER,INTEGER,INTEGE*/
#define MUL 3			/*MUL,INTEGER,INTEGER,INTEGE*/
#define UDIV 4			/*UDIV,INTEGER,INTEGER,INTEGE*/
#define ALLOC 5			/*ALLOC,POINTER,INTEGER*/
#define STORE 6			/*STORE,,INTEGER,POINTER*/
#define LOAD 7			/*LOAD,INTEGER,POINTER*/
#endif
